#!/bin/sh

if [ $3 == '1' ]
then
	branch=$(git rev-parse --abbrev-ref HEAD)
	if [[ $branch == release/* ]]
	then
		if [[ $branch =~ release/([0-9.]*)$ ]]
		then
			./Tools/setVersion.sh ${BASH_REMATCH[1]} ./
		fi
	fi
fi