osx_image: beta-xcode6.3
xcode_workspace: seguecode.xcworkspace
xcode_scheme: 
- seguecodePluginLocal
- seguecodePlugin
before_install: 
- gem install cocoapods
- git submodule init
- git submodule update