//
//  DefaultTemplate.swift
//  seguecode
//
//  Created by Ian Grossberg on 8/21/15.
//  Copyright (c) 2015 Adorkable. All rights reserved.
//

import Cocoa

import Stencil

class DefaultTemplate: Template {
    struct Keys
    {
        static let FileName = "FileName"
        static let ProjectName = "ProjectName"
        
        static let GeneratedOn = "GeneratedOn"
        
        static let ViewControllers = "ViewControllers"
        struct ViewController {
            static let Name = "ViewControllerName"
            
            static let SegueCases = "SegueCases"
            struct SegueCase
            {
                static let Identifier = "Identifier"
                static let SourceIdentifier = "SourceIdentifier"
                static let DestinationIdentifier = "DestinationIdentifier"
                static let Value = "Value"
            }
            
            static let PerformFunctions = "PerformFunctions"
            struct PerformFunction
            {
                static let Identifier = "Identifier"
                static let SourceIdentifier = "SourceIdentifier"
                static let DestinationIdentifier = "DestinationIdentifier"
            }
        }
    }
    
    static var topFileComments : String {
        return "//\n" +
        "{% if \(Keys.FileName) %}" +
        "//  {{ \(Keys.FileName) }}\n" +
        "{% endif %}" +
        "{% if \(Keys.ProjectName) %}" +
        "//  {{ \(Keys.ProjectName) }}\n" +
        "{% endif %}" +
        "//\n" +
        "//  Generated by seguecode [http://bit.ly/seguecode]" +
        "{% if \(Keys.GeneratedOn) %}" +
        " on {{ \(Keys.GeneratedOn) }}\n" +
        "{% endif %}" +
        // TODO: copywrite and company info
        "//"
    }

    static var segueCases : String {
        return "{% if viewController.\(Keys.ViewController.SegueCases) %}" +
            "\n" +
            "   struct Segues {\n" +
            "{% for segueCase in viewController.\(Keys.ViewController.SegueCases) %}" +
            "       static let {{ segueCase.\(Keys.ViewController.SegueCase.SourceIdentifier) }}{{ segueCase.\(Keys.ViewController.SegueCase.Identifier) }}{{ segueCase.\(Keys.ViewController.SegueCase.DestinationIdentifier) }} = Segue(identifier: \"{{ segueCase.\(Keys.ViewController.SegueCase.Value) }}\")\n" +
            "{% endfor %}" +
            "   }\n" +
            "{% endif %}"
    }
    static var performFunctions : String {
        return "{% if viewController.\(Keys.ViewController.PerformFunctions) %}" +
            "{% for performFunction in viewController.\(Keys.ViewController.PerformFunctions) %}" +
            "\n" +
            "   @IBAction func perform{{ performFunction.\(Keys.ViewController.PerformFunction.SourceIdentifier) }}{{ performFunction.\(Keys.ViewController.PerformFunction.Identifier) }}{{ performFunction.\(Keys.ViewController.PerformFunction.DestinationIdentifier) }}(sender : AnyObject? = nil) {\n" +
            "       self.performSegue({{ viewController.\(Keys.ViewController.Name) }}.Segues.{{ performFunction.\(Keys.ViewController.PerformFunction.SourceIdentifier) }}{{ performFunction.\(Keys.ViewController.PerformFunction.Identifier) }}{{ performFunction.\(Keys.ViewController.PerformFunction.DestinationIdentifier) }}, sender: sender)\n" +
            "   }\n" +
            "{% endfor %}" +
            "{% endif %}"
    }
    
    static var sourceFile : String {
        return self.topFileComments + "\n" +
            "\n" +
            "import UIKit\n" +
            "{% if \(Keys.ViewControllers) %}" +
            "{% for viewController in \(Keys.ViewControllers) %}" +
            "\n" +
            "extension {{ viewController.\(Keys.ViewController.Name) }} {\n" +
            self.segueCases +
            self.performFunctions +
            "}\n" +
            "{% endfor %}" +
            "{% endif %}"
    }
    
    required init() {
        super.init(templateString: DefaultTemplate.sourceFile)
    }
}
